server:
  port: 8083
spring:
  application:
    name: ${APPLICATION_NAME:ride-service}
  data:
    mongodb:
      uri: mongodb://localhost:28017/ride_db
  messages:
    basename: message-constant
  integration:
    passenger-url: http://localhost:8081/api/v1/passengers
  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost:9092}
    producer:
      group-id: driver
      topic:
        driver-topic: ride-driver-topic

router:
  link: https://api.openrouteservice.org/v2/directions/driving-car/json
  apiKey: ${APIKEY:key-val}

springdoc:
  api-docs:
    path: /api/v1/rides/docs
  swagger-ui:
    path: /api/v1/rides/swagger-ui.html

logging:
  level:
    org.modsen.client: DEBUG